1. What is the purpose of the "Applied Steps" pane in Power Query?

The Applied Steps pane (on the right side of Power Query Editor) lists each transformation applied to your data — for example: “Removed Columns,” “Filtered Rows,” “Renamed Columns.”
✅ You can:

Edit, delete, or reorder these steps.

Track your entire data cleaning process.

2. How do you remove duplicate rows in Power Query?

Go to Home → Remove Rows → Remove Duplicates.

Power Query removes identical rows based on all columns (or selected columns if chosen first).

3. What does the "Filter" icon do in Power Query?

The Filter icon (next to each column header) lets you:

Filter specific values (e.g., only “Laptop”).

Apply number/date/text filters (e.g., Price > 100).
✅ Works similar to Excel’s filter feature but is applied as a transformation step.

4. How would you rename a column from "CustID" to "CustomerID"?

Right-click the column header CustID → Rename → type "CustomerID".
Or use M-code:

Table.RenameColumns(Source, {{"CustID", "CustomerID"}})

5. What happens if you click "Close & Apply" in Power Query?

Power Query saves all transformations and loads the cleaned data back into Power BI Desktop.

The query editor closes, and your dataset refreshes with updated changes.

6. Remove all rows where Quantity is less than 2.

In Power Query:

Click Filter icon on Quantity column → choose Number Filters → Greater Than or Equal To → 2.

M-code:

Table.SelectRows(Source, each [Quantity] >= 2)


✅ Keeps only orders where Quantity ≥ 2.

7. Split the OrderDate column into separate "Year," "Month," and "Day" columns.

Steps:

Select OrderDate column → Add Column → Date → Year / Month / Day → Year / Month / Day.

M-code:

= Table.AddColumn(Source, "Year", each Date.Year([OrderDate]))


(similarly for Month and Day).

8. Replace all "Mouse" entries in the Product column with "Computer Mouse."

Select Product → Transform tab → Replace Values.

Find: Mouse → Replace With: Computer Mouse.

M-code:

Table.ReplaceValue(Source, "Mouse", "Computer Mouse", Replacer.ReplaceText, {"Product"})

9. Sort the table by OrderDate (newest first).

Click the OrderDate column header → Sort Descending.

M-code:

Table.Sort(Source, {{"OrderDate", Order.Descending}})

10. How would you handle null values in the Price column?

Options:

Replace nulls with a default value (e.g., 0):
Transform → Replace Values → Replace null with 0

Remove null rows:
Home → Remove Rows → Remove Blank Rows

Use conditional logic:
Add a column: if [Price] = null then 0 else [Price].

11. Write custom M-code to add a column calculating TotalSpent = Quantity * Price.
Table.AddColumn(Source, "TotalSpent", each [Quantity] * [Price])


✅ Adds a new column with the total spend per order.

12. Group the table by CustID to show total spending per customer.

Steps:

Go to Home → Group By.

Group by: CustID

New column name: TotalSpent

Operation: Sum of TotalSpent (or Quantity * Price).

M-code:

Table.Group(Source, {"CustID"}, {{"TotalSpent", each List.Sum([Quantity] * [Price]), type number}})

13. Fix inconsistent date formats (e.g., 01/10/2023 vs. 2023-01-10) in OrderDate.

Change data type to Date:
Transform → Data Type → Date
Power Query automatically parses various formats.
If not consistent, use:

Table.TransformColumns(Source, {{"OrderDate", each Date.FromText(Text.From(_)), type date}})

14. Create a conditional column: Label orders as "High Value" if Price > 100.

Go to Add Column → Conditional Column.

Condition: Price > 100 → "High Value", else "Regular".

M-code:

Table.AddColumn(Source, "OrderLabel", each if [Price] > 100 then "High Value" else "Regular")

15. Optimize the query to reduce refresh time (e.g., remove unused columns early).

Best practices:

Remove unnecessary columns early in the query (fewer columns = faster refresh).

Filter rows early to limit data volume.

Disable background previews when working with large data.

Combine queries efficiently (avoid multiple merges if possible).

Example:

#"Removed Columns" = Table.RemoveColumns(Source,{"Email","Name"})


✅ Bonus Tip:
You can merge Orders with Customer_orders using CustID to enrich your data:

Table.NestedJoin(Orders, {"CustID"}, Customer_orders, {"CustID"}, "CustomerInfo", JoinKind.Inner)
